usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: --work-class=gevent
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: --work-class=gevent

Error: class uri 'gevent' invalid or not found: 

[Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 134, in load_class
    mod = import_module('.'.join(components))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 22, in <module>
    raise RuntimeError("You need gevent installed to use this worker.")
RuntimeError: You need gevent installed to use this worker.
]


Error: class uri 'gevent' invalid or not found: 

[Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 134, in load_class
    mod = import_module('.'.join(components))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 22, in <module>
    raise RuntimeError("You need gevent installed to use this worker.")
RuntimeError: You need gevent installed to use this worker.
]

[2018-01-24 12:48:16 +0000] [1013] [INFO] Starting gunicorn 19.7.1
[2018-01-24 12:48:16 +0000] [1013] [INFO] Listening at: http://127.0.0.1:8000 (1013)
[2018-01-24 12:48:16 +0000] [1013] [INFO] Using worker: sync
[2018-01-24 12:48:16 +0000] [1017] [INFO] Booting worker with pid: 1017
[2018-01-24 12:48:16 +0000] [1017] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ImportError: No module named conference.wsgi
[2018-01-24 12:48:16 +0000] [1017] [INFO] Worker exiting (pid: 1017)
[2018-01-24 12:48:16 +0000] [1013] [INFO] Shutting down: Master
[2018-01-24 12:48:16 +0000] [1013] [INFO] Reason: Worker failed to boot.
[2018-01-24 12:51:42 +0000] [1057] [INFO] Starting gunicorn 19.7.1
[2018-01-24 12:51:42 +0000] [1057] [INFO] Listening at: http://127.0.0.1:8000 (1057)
[2018-01-24 12:51:42 +0000] [1057] [INFO] Using worker: sync
[2018-01-24 12:51:42 +0000] [1061] [INFO] Booting worker with pid: 1061
[2018-01-24 12:51:42 +0000] [1061] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ImportError: No module named conference.wsgi
[2018-01-24 12:51:42 +0000] [1061] [INFO] Worker exiting (pid: 1061)
[2018-01-24 12:51:42 +0000] [1057] [INFO] Shutting down: Master
[2018-01-24 12:51:42 +0000] [1057] [INFO] Reason: Worker failed to boot.
